### ISSUE TITLE
What does the 'propTypes' means in components/body.js

### ISSUE THREAD

**Issue by xiaoyaojian** [BiosBoy/coconat#16]
I found some code blow

```
 static propTypes = {
    imageToShow: PropTypes.number,
    switchImage: PropTypes.func
  }
```
I don't understand the meaning of that, I can't find anywhere ref this variable?

**Comment by BiosBoy** [comment]
Hi!

```static propTypes``` is a new ES6 feature that allows you to define the static properties of your class for ordinary usage.

Look on this article for more info: https://medium.com/@assortedPickle/es6-static-properties-b7fd2a163328

**Comment by xiaoyaojian** [comment]
Thank you, sir, I'm not familiar with es6 feature...awkward
