### ISSUE TITLE
how do used for injecting a saga in a lazy-loaded route

### ISSUE THREAD

**Issue by pandaCure** [BiosBoy/coconat#20]
i read redux-saga-watch-actions document, i find this what does't support react-router >= 4.0
so can you gave some example?

this is redux-saga-watch-actions document link
https://heygrady.github.io/redux-saga-watch-actions/docs/middleware/injectSaga.html

**Comment by BiosBoy** [comment]
Hi @pandaCure !

Actually, I don't think that this is a problem for now, because all works fine, including sagas. If you found some problems during the compilation process or navigation with sagas, feel free to contact me.

Thanks!
