### ISSUE TITLE
why don't use webpack dev server

### ISSUE THREAD

**Issue by Jazk-Z** [BiosBoy/coconat#22]
I see you about weboack.config, this options entry include webpack-hot-middleware, this is old config, and create-react-app also use this, i don't understand this, why not use about webpack dev server that also suppurt node cli, canyou help me

**Comment by BiosBoy** [comment]
Hi @Jazk-Z !

Thanks for your report. Well, I would say it's just a question of taste. Probably, CRA, as well as I just don't have enough time to deal with up to date solutions. Anyway, all seems to works great.

So, if you have an opportunity, I would be glad and excited to see your PR in favor of upgrading current webpack server configuration.

Thanks.
