### ISSUE TITLE
Keep the branch without TypeScript

### ISSUE THREAD

**Issue by Kostanos** [BiosBoy/coconat#23]
I see your article [here](https://blog.usejournal.com/lets-kill-create-react-app-452cb55f77d3), which is great, and thank you for that.

But now, I see you switching to TypeScript.
Is it possible for you to create and maintain separate branch without TypeScript migration?

**Comment by BiosBoy** [comment]
Hi, @Kostanos .
First of all thanks for your interesting! 

Well, you can write your apps using **Coconat Starter Kit Builder** on both (or separate) JS and TS languages (the last one is a pre-processor actually). It was the main point from very beginning - provide an ability to choose the language to work with. So, to be honest I don't know about which switch you're talking about :(, sorry. Even now, you can start coding your app on the pure `.js` without any afforts and tears.

If you need some help feel free to contact me. Thanks.

**Comment by Kostanos** [comment]
Hi, I think I didn't explained myself clean.
Your article that I following despite is having few minor mistakes, is very good, and gives short, understandable introduction to React based environment.
And all scripts that you have in your repository serves me, and I'm sure to many others as a start base example.
The reason why I'm asking to keep JS branch apart, is because for example you already have: 
`coconat/src/components/Body.tsx` but no `coconat/src/components/Body.js`, and as I understand, you are moving all your scripts to TS.
I personally don't like TS, and would like to keep my code in JS, in the case of your script, I needed to find in the git history the original Body.js, and several other files.

The simple solution for this, is to create a TAG or a Branch with the name like: *JS before TS* or *Full JS version* etc... 
Thank you.
